<div class="container rounded bg-white mt-5">
    <div class="row">
        <div class="col-md-4 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" src="https://i.imgur.com/0eg0aG0.jpg" width="90"><span class="font-weight-bold"><?php echo $data->getUsername(); ?></span><span class="text-black-50"><?php echo $data->getEmail(); ?></span><span>Chức vụ: <?php echo $data->getRole(); ?></span></div>
        </div>
        <div class="col-md-8">
            <div class="p-3 py-5">
                
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <div class="d-flex flex-row align-items-center back"><i class="fa fa-long-arrow-left mr-1 mb-1"></i>    
                        <a class="nav-link" href="<?= $this->url('home'); ?>">Quay lại trang chủ</a>
                    </div>
                </div>
                <div class="row mt-2">
                    <a href="<?= $this->url('settings', ['action' => 'password']); ?>" class="nav-link">
					<button class="btn btn-outline-success" type="button">Thay đổi mật khẩu</button>
					</a>
                </div>
                <div class="row mt-3">
                   <a href="<?= $this->url('settings', ['action' => 'username']); ?>" class="nav-link">
					<button class="btn btn-outline-success" type="button">Thay đổi tên người dùng</button>
				</a>
                </div>
                <div class="row mt-3">
                    <a href="<?= $this->url('settings', ['action' => 'delete']); ?>" class="nav-link">
					<button class="btn btn-outline-success" type="button">Xóa tài khoản</button>
				</a>
                </div>

            </div>
        </div>
    </div>
</div>
